version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # React 開発サーバーのポート
    volumes:
      - ./frontend:/app
    command: npm run start
    depends_on:
      - backend   # バックエンドが起動するのを待つ

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Express サーバーのポート
    volumes:
      - ./backend:/app
    command: npm run start  # 修正
    environment:
      - DB_HOST=db
      - DB_USER=hackathon_user
      - DB_PASS=hackathon_pass
      - DB_NAME=hackathon
    depends_on:
      - db  # データベースが起動するのを待つ

  db:
    image: mysql:8.0
    container_name: hackathon-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hackathon
      MYSQL_USER: hackathon_user
      MYSQL_PASSWORD: hackathon_pass
    ports:
      - "3306:3306"  # MySQLのポート設定
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db         # MySQLホスト名
      - PMA_USER=hackathon_user  # MySQLのユーザー名
      - PMA_PASSWORD=hackathon_pass  # MySQLのパスワード
    ports:
      - "8080:80"  # phpMyAdminが動作するポート
    depends_on:
      - db  # DBコンテナが起動するのを待つ

volumes:
  db_data:
